 [tool.poetry]
name = "compound-ai-systems"
version = "0.1.0"
description = ""
authors = ["yudhisteer <yudhisteer.chin@gmail.com>"]
readme = "README.md"
package-mode = false  # Add this line

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
ag2 = "^0.7.5"
python-dotenv = "^1.0.1"
black = "^25.1.0"
isort = "^6.0.0"
openai = "^1.63.2"
pydantic = "^2.6.1"
requests = "^2.32.3"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
