 [tool.poetry]
name = "compound-ai-systems"
version = "0.1.0"
description = ""
authors = ["yudhisteer <yudhisteer.chin@gmail.com>"]
readme = "README.md"
package-mode = false  # Add this line

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
ag2 = "0.7.5"
python-dotenv = "1.0.1"
black = "25.1.0"
isort = "6.0.0"
openai = "1.63.2"
pydantic = "2.10.6"
requests = "2.32.3"
wikipedia = "1.4.0"
colorlog = "6.9.0"
aiofiles = "24.1.0"
annotated-types = "0.7.0"
anyio = "4.8.0"
asttokens = "3.0.0"
asyncer = "0.0.8"
beautifulsoup4 = "4.13.3"
certifi = "2025.1.31"
cffi = "1.17.1"
charset-normalizer = "3.4.1"
click = "8.1.8"
colorama = "0.4.6"
comm = "0.2.2"
cryptography = "44.0.2"
debugpy = "1.8.12"
decorator = "5.2.1"
diskcache = "5.6.3"
distro = "1.9.0"
docker = "7.1.0"
ecdsa = "0.19.1"
executing = "2.2.0"
fast-depends = "2.4.12"
fastapi = "0.115.11"
h11 = "0.14.0"
hiredis = "3.1.0"
httpcore = "1.0.7"
httpx = "0.28.1"
idna = "3.10"
ipykernel = "6.29.5"
ipython = "9.0.0"
ipython-pygments-lexers = "1.1.1"
jedi = "0.19.2"
jiter = "0.8.2"
jupyter-client = "8.6.3"
jupyter-core = "5.7.2"
matplotlib-inline = "0.1.7"
more-itertools = "10.6.0"
mypy-extensions = "1.0.0"
nest-asyncio = "1.6.0"
numpy = "2.2.3"
packaging = "24.2"
pandas = "2.2.3"
parso = "0.8.4"
pathspec = "0.12.1"
platformdirs = "4.3.6"
prompt-toolkit = "3.0.50"
psutil = "7.0.0"
psycopg2-binary = "2.9.10"
pure-eval = "0.2.3"
pyasn1 = "0.4.8"
pyautogen = "0.7.5"
pycparser = "2.22"
pydantic-core = "2.27.2"
pygments = "2.19.1"
python-dateutil = "2.9.0.post0"
python-decouple = "3.8"
python-jose = "3.4.0"
python-multipart = "0.0.20"
python-ulid = "1.1.0"
pytz = "2025.1"
pywin32 = "308"
pyzmq = "26.2.1"
redis = "5.2.1"
redis-om = "0.3.3"
regex = "2024.11.6"
rsa = "4.9"
six = "1.17.0"
sniffio = "1.3.1"
soupsieve = "2.6"
sseclient-py = "1.8.0"
stack-data = "0.6.3"
starlette = "0.46.1"
termcolor = "2.5.0"
tiktoken = "0.9.0"
tornado = "6.4.2"
tqdm = "4.67.1"
traitlets = "5.14.3"
types-cffi = "1.17.0.20250319"
types-pyopenssl = "24.1.0.20240722"
types-redis = "4.6.0.20241004"
types-setuptools = "76.0.0.20250313"
typing-extensions = "4.12.2"
tzdata = "2025.1"
urllib3 = "2.3.0"
uvicorn = "0.34.0"
wcwidth = "0.2.13"
websockets = "14.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
